#!/bin/bash

bgDir="$HOME/.me/bgs/"
dwm="/home/db/Local/suckless/dwm"
dmenu="/home/db/Local/suckless/dmenu"

pre () {
  if [ ! -n "$bgDir" ]; then
    echo "background image firectory not found" && exit 1
  fi

  sxiv -v 1>/dev/null || echo "sciv not installed"
  feh -v 1>/dev/null || echo "feh not installed"
}

selectImage (){
  bgImage="$(sxiv -o -r -t $bgDir)"
  if [ -z "$bgImage" ]; then alert "Oops!" "No image selcted, exitting.." && exit 1 ; fi
}

setWallpaper (){
  feh --bg-fill --no-xinerama "$1"
}

createColorscheme () {
  wal -i "$bgImage"
}

buildSuckless() {
  cd $dwm && sudo make clean install
  cd $dmenu && sudo make clean install
}

setXresources () {
  cat ~/.cache/wal/colors.Xresources > ~/.Xresources && xrdb ~/.Xresources
}

reloadWindowmanager () {
  xdotool key Super_L+Shift_L+q
}

firefoxCSS () {
  #check if multiple user profiles exsist
  if [[ $(find ~/.mozilla/firefox/ -type d -iname "*.default" | wc -l) -gt 1 ]]; then
    echo "More then one user profile exsist, please hard code you prefered profile in the script."
    exit 1
  fi
  folder=$(echo "$HOME"/.mozilla/firefox/*.default)
  if [ ! -d  "$folder/chrome" ]; then
     mkdir -p "$folder/chrome"
     echo "chrome folder created."
  fi
  cp -f ./build/firefox/userContent.css "$folder/chrome"
  cp -f ./build/firefox/userChrome.css "$folder/chrome"

  local chrome="$(echo $folder/chrome/userChrome.css)"
  local content="$(echo $folder/chrome/userContent.css)"

  if [[ $(head -n 1 "$chrome" | grep -c "/* CSS variables") -eq 1 ]]; then
    sed -i 1,28d "$chrome"
    cat "$HOME/.cache/wal/colors.css" "$chrome"> temp && mv temp "$chrome"
  fi

  if [[ $(head -n 1 "$content" | grep -c "/* CSS variables") -eq 1 ]]; then
    sed -i 1,28d "$content"
    cat "$HOME/.cache/wal/colors.css" "$content"> temp && mv temp "$content"
  fi

  alert "Done!" "Firefox CSS set succesfully."
}

qutebrowserCSS (){
  command -v qutebrowser 1>/dev/null || { echo "Qutebrowser not installed, skipping..."; return 1; }

  if [[ $(cat $HOME/.config/qutebrowser/config.py | grep -c "import pywalQute.draw") -eq 1 ]]; then
    echo "Plugin already installed, skipping... checking if pywalQute folder exsist:"
  fi

  if [ -z .config/qutebrowser/pywalQute/ ]; then
    echo "pywalQute folder is there." || { echo "Qutebrowser exention seems to be installed correctly, continueing..."; return 1; }
  elif [ ! -d .config/qutebrowser/pywalQute/ ]; then
    cp -r ./build/pywalQute/ $HOME/.config/qutebrowser
    echo "pywalQute folder installed."
  fi
  echo "$( cat ./build/pywalQute/snippet )" >> "$HOME/.config/qutebrowser/config.py"
}

alert (){
  notify-send --icon="$3" "$1" "$2"
}


selectImage
setWallpaper "$bgImage" && alert "Done!" "Background image is set" "$bgImage"
createColorscheme && alert "Done!" "Colorscheme is set" "$bgImage"
buildSuckless && alert "Suckless build suckessfully."  "$bgImage"
setXresources
firefoxCSS
qutebrowserCSS
reloadWindowmanager
