#!/bin/bash

bgDir="$HOME/.me/bgs/"


pre () {
  if [ ! -n "$bgDir" ]; then
    echo "background image firectory not found" && exit 1
  fi

  sxiv -v 1>/dev/null || echo "sciv not installed"
  feh -v 1>/dev/null || echo "feh not installed"
}

selectImage (){
  bgImage="$(sxiv -o -r -t $bgDir)"
  if [ -z "$bgImage" ]; then alert "Oops!" "No image selcted, exitting.." && exit 1 ; fi
}

setWallpaper (){
  feh --bg-fill --no-xinerama "$1"
}

createColorscheme () {
  wal -i "$bgImage"
}

buildSuckless() {
  kitty sudo sucklessInstall
}

setXresources () {
  cat ~/.cache/wal/colors.Xresources > ~/.Xresources && xrdb ~/.Xresources
}

reloadWindowmanager () {
  xdotool key Super_L+Shift_L+q
}

browserCSS () {
  #check if multiple user profiles exsist
  if [[ $(find ~/.mozilla/firefox/ -type d -iname "*.default" | wc -l) -gt 1 ]]; then
    echo "More then one user profile exsist, please hard code you prefered profile in the script."
    exit 1
  fi
  folder=$(echo "$HOME"/.mozilla/firefox/*.default)
  if [ ! -z  "$folder/chrome" ]; then
     mkdir -p "$folder/chrome"
     echo "chrome folder created."
  fi
  cp ./build/userContent.css "$folder"
  # sed -i 1,28d  ~/.mozilla/firefox/lk2u0692.default/chrome/user*
}

alert (){
  notify-send --icon="$bgImage" "$1" "$2"
}


# pre
# selectImage
# setWallpaper "$bgImage" && alert "Done!" "Background image is set" "$bgImage"
# createColorscheme && alert "Done!" "Colorscheme is set" "$bgImage"
# buildSuckless
# setXresources
# reloadWindowmanager

browserCSS
